name: Docker Image CI & Publish Docker

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nodejs-dcmtk:$(date +%s)

    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: michaelleehobbs/nodejs-dcmtk
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_with_ref: true
        tag_with_sha: true
        push: ${{ startsWith(github.ref, 'refs/heads/r') }}
